plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

# RSpec configurations
RSpec/ExampleLength:
  Max: 20 # Allow longer examples

RSpec/MultipleExpectations:
  Max: 5 # Allow up to 5 expectations per example

RSpec/NestedGroups:
  Max: 4 # Allow up to 4 levels of nesting

RSpec/SpecFilePathFormat:
  Enabled: false # Disable the path format requirement

RSpec/SpecFilePathSuffix:
  Enabled: false # Disable file path suffix requirement

RSpec/DescribeClass:
  Enabled: false # Allow top-level describes without class/module
